language: java
jdk:
  - openjdk11

services:
  - postgresql

before_install:
  - psql -c 'create database dreamjob;' -U postgres
sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)


notifications:
  email:
    recipients:
      -d.krylovk@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
    env:
      global:
        - CODECOV_TOKEN="fffe1753-62f0-42f5-b411-36d7533d5187"